### ISSUE TITLE
mv-modal component

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/mv-modal#1]

**Comment by kullervo21** [comment]
Creation of a new modal component that can contain multiple slots for content. This component should function as a standard modal window and be able to display on top of all other components, dimming the background. It should also have a close button or a way to close it by clicking outside the modal window.

The new modal component should have slots, which will allow different types of content to be inserted, such as header, main content, and footer.

**Comment by kullervo21** [comment]
timeSpent: 6
